Resolve #13 -- Added skin select
MatthewFrench/LeagueUI pull request #14
Opened 2016-12-25 21:03 UTC by coquicox

Added skin select
More adapted for smaller screens
Some fancy button

Refs #13

2016-12-25 22:11 UTC, MatthewFrench commented
Looks good to me.

2016-12-25 22:17 UTC, MatthewFrench approved these changes
Looks good.

2016-12-26 11:38 UTC, MythicManiac requested changes
When you make changes, add the "Refs #13" to the commit message as well (currently found only on PR message)

No other complaints

2016-12-26 11:38 UTC, MythicManiac commented on Client/Javascript/MainPage.js
> +var extendedChampData = {
Could this be moved to a json file or something the like?

2016-12-26 17:26 UTC, MythicManiac approved these changes

2016-12-26 17:27 UTC, merged